#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu "$@")


[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
  t=$(pass show "$password")
  filtered=$(printf '%s' "$t" | tail -n +3 | sed 's/:.*//' | cat - <(printf "\npassword"))
  action=$(printf '%s\n' "${filtered}" | rofi -dmenu "$@")


  if [[ $action == "password" ]]; then
    notify-send "Password in clipboard" -t 2000
    pw=$(pass show "$password" | head -1)
    wl-copy "$pw"
    sleep 2s && wl-copy -c && exit
  else
    notify-send "$action in clipboard" -t 2000
    txt=$(pass show "$password" | sed -n "s/$action: //p")
    wl-copy "$txt"
    sleep 2s && wl-copy -c && exit
  fi

fi

