#!/usr/bin/env bash

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -i -dmenu "$@")


[[ -n $password ]] || exit

t=$(pass show "$password")
tags=$(printf '%s' "$t" | tail -n +3 | sed 's/:.*//')
filtered=$(printf "autotype\npassword\n%s\n" "$tags")
action=$(printf '%s\n' "${filtered}" | rofi -dmenu "$@")

if [[ $action == "password" ]]; then
  pw=$(pass show "$password" | head -1)
  wtype "$pw"
elif [[ $action == "autotype" ]]; then
  txt=$(pass show "$password" | sed -n "s/$action: //p")
  [[ -n $txt ]] || txt="user :tab pass" # default autotype
  actionstring=""
  for word in $txt
  do
    if [[ $word == ":tab" ]]; then
      wtype -P TAB
    elif [[ $word == "pass" ]]; then
      pw=$(pass show "$password" | head -1)
      # remove newline at the end
      echo -n "$pw" | wtype -
    else
      # fetch value of key
      wtype $(pass show "$password" | grep $word: | sed 's/.*: //')
    fi
  done
else
  txt=$(pass show "$password" | sed -n "s/$action: //p")
  wtype "$txt"
fi

